apiVersion: v1
kind: Service
metadata:
  name: vnode-loadbalancer-service
  labels:
    app: vnode-nginx
spec:
  type: LoadBalancer
  selector:
    app: vnode-nginx
  ports:
    - port: 80
      targetPort: 80
