apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-app1-deployment
  labels:
    app: windows-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-app1  
  template:
    metadata:
      name: windows-app1
      labels:
        app: windows-app1
    spec:
# To schedule pods on based on NodeSelectors      
      nodeSelector:
        #"beta.kubernetes.io/os": windows
        app: dotnet-apps
      containers:
      - name: windows-app1
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80

